### ISSUE TITLE
confirm SAFE guideline links are most current

### ISSUE THREAD

**Issue by mkapur-noaa** [afsc-assessments/sop#8]
https://github.com/afsc-assessments/sop/blob/41b0818a506d3bf9d0450a36f1db6826b0f5c7ca/03-safe.Rmd#L8

I notice this links to a 2016 version of the safe guidelines, though (according to my Chrome history) there is a newer version here: https://docs.google.com/document/d/1IAjzi_0Lkobh5IimucJVn32Y7deU_j14aXVshqNVNw8/edit#heading=h.gjdgxs

(But I haven't cross checked to see if the versions are qualitatively distinct)

**Comment by BenWilliams-NOAA** [comment]
updated to most current (2020)
